#!/bin/bash

# Script to sync the bundle directory from git repos and then rsync to
# the new-host-setup dir.

# 1. git refresh all of the bundle dirs.
# 2. rsync the bundle dir with the master bundle dir.

cd $(dirname $0)/bundle
bundledir=$(pwd)

for i in $(find . -maxdepth 1 ! -name "." -type d -print)
do
    cd "$bundledir/$i"
    echo $i
    git pull
done

# vim:sts=4:sw=4:ts=4:tw=76
